### ISSUE TITLE
Labels mismatch when training on coco2017

### ISSUE THREAD

**Issue by AyushExel** [Laughing-q/yolov5-q#6]
<img width="530" alt="Screenshot 2022-07-11 at 9 26 25 PM" src="https://user-images.githubusercontent.com/15766192/178306253-89f7e633-82ac-41d5-96bf-169a8f864dfa.png">
I got this error while trying to train on coco dataset. It originates from `computeLoss` operation. I think the `nc` is set to 80 for coco.yaml but segmentation labels go upto 91. Maybe that is the problem? 
I saw that `coco80_to_coco91_class` function is used for evaluation but not for computeLoss.. Maybe that's the problem?

**Comment by Laughing-q** [comment]
@AyushExel did you convert coco labels to yolo txt by yourself? I just use the converted txt labels from official yolov5 [coco-segment](https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels-segments.zip), which  the `nc` is 80. It works for me. After training, the function `coco80_to_coco91_class` is used to evaluation.

**Comment by AyushExel** [comment]
no I'm just using the dataset from ultralytics as well with nc set to 80

**Comment by Laughing-q** [comment]
@AyushExel did you use the `master` branch?
I'll try to reproduce this issue tomorrow.

**Comment by AyushExel** [comment]
@Laughing-q here's where I think the error is originating from..
https://github.com/Laughing-q/yolov5-q/blob/897b6fd812b1163714d28e83c2b661fe3473439b/yolov5/models/loss.py#L327
For batch size 16, running on coco128 segments, this is the dimensions, which works.

<img width="379" alt="Screenshot 2022-07-11 at 11 03 30 PM" src="https://user-images.githubusercontent.com/15766192/178324422-13187ebe-abec-4265-825e-d5b876174801.png">
But for the same batch size training on entire coco segments dataset, I get these dimensions, which seems to be the problem.
<img width="261" alt="Screenshot 2022-07-11 at 11 04 23 PM" src="https://user-images.githubusercontent.com/15766192/178324619-484015ca-4e6b-4a98-80e3-42ac9fbab74f.png">

I don't know what's the cause here can be.. But maybe this will be helpful for debugging. I'm trying to run this training like original yolov5 trainer to make it compatible

**Comment by AyushExel** [comment]
@Laughing-q ok I think I found the problem..I was passing  `--hyp hyp.scratch-med.yaml` like when training for detection. removing that part fixed the problem. Not sure what the reason was.. Or maybe some hyper-parameter was messing with the masks code

**Comment by AyushExel** [comment]
@Laughing-q ok so the above problem was solved but I think there are 2 more issues, and maybe I've done something wrong here.
Note: i'm training with mask-ratio 4
* When calling `plot_images_boxes_and_masks` in evaluator, this warning gets thrown and masks are not plotted.
`    return plot_images_and_masks(images, targets, masks, paths, fname, names, max_size, max_subplots)
  File "/usr/src/yolov5/utils/plots.py", line 1268, in plot_images_and_masks
    mosaic[block_y : block_y + h, block_x : block_x + w, :][mask] = mosaic[
IndexError: boolean index did not match indexed array along dimension 0; dimension is 448 but corresponding boolean dimension is 112`
If you see the dim 448 is 4 times 112..I think this means somewhere the mask-ratio of 4 is not being accounted for.

* the 2nd problem is that each epoch takes almost ~30mins on A100.. While the model (yolov5m with 22M params) takes 10 mins for each epoch when training from original yolov5 for detection only. Should mask training take 3x more time? I'm not sure maybe I've introduced a but in dataloader

**Comment by AyushExel** [comment]
@Laughing-q OK I think this test confirms the plotting bug..Even after a few epochs when Mask Map is 28.8%, the masks are not plotted in the predictions plot. See this run all metrics and media - https://wandb.ai/cayush/YOLOv5-Inst-seg/runs/1etryi2f
<img width="788" alt="Screenshot 2022-07-12 at 9 38 39 AM" src="https://user-images.githubusercontent.com/15766192/178406612-4e8f7770-5265-4f66-bdd1-bac00a7a6931.png">

**Comment by Laughing-q** [comment]
`plots=True` and `mask_ratio=1` are bound, cause plotting needs high-quality masks. The function `plot_images_and_masks` is set to accept high-quality masks as input. Plotting images will occupy a lot of cuda memory in my situation, so I set `plots=False` as default when training. Set `plots=True` when I do evaluation after training which use high-quality masks. And this workflow works fine with me.

I was training on a small dataset with `plots=True` and `mask_ratio=1`, trying to reproduce your plot issue which got bbox only.
here are my `pred_images`:

with low mAP:
![val_batch0_pred1](https://user-images.githubusercontent.com/61612323/178416028-39118861-9cf2-4998-90dc-205b87b97992.jpg)

with a little higher mAP:
![val_batch0_pred](https://user-images.githubusercontent.com/61612323/178416040-93cd71ab-79d6-4768-8a24-fd77ef044f2b.jpg)

Even with low mAP and incorrect predictions, I got both bboxes and masks.

As for the training time, yes training segmentation does slow down the training speed. Cause the extra masks are loaded when dataloading. There is another thing I care about when computing loss, computing bbox loss is in multi-level feature map dims from official yolov5, but masks loss need be computed in batch-size level [https://github.com/Laughing-q/yolov5-q/blob/897b6fd812b1163714d28e83c2b661fe3473439b/yolov5/models/loss.py#L346](https://github.com/Laughing-q/yolov5-q/blob/897b6fd812b1163714d28e83c2b661fe3473439b/yolov5/models/loss.py#L346)
I think this slow down the training speed either. If you have any ideas to speed up the training, please let me know!

**Comment by AyushExel** [comment]
@Laughing-q hey man! first of all thanks for responding to this. I might have introduced some bug while refactoring the code. What i'm doing is setting up a very basic baseline for instance segmentation using official yolov5 training script so that we can use it as a starting point for R&D and maybe someday officially support it in yolov5.

I'll try to train again with yolov5s_seg.yaml and with both `plots=True` and `mask_ratio=1` .. Once I figure this out I'll try to improve the performance if possible..Thanks again

**Comment by Laughing-q** [comment]
@AyushExel The original intention of this project is to do an instance segmentation based on yolov5. It's just I don't have enough time and devices for this. 
Here are some experimental results I remembered. 
The argument `no_aug_epoch` will decrease mAP, and the performance of `yolov5l_seg` is worse then `yolov5m_seg` which confused me(this is also why I didn't release the weight of yolov5l_seg), maybe it's because the mask head is too simple.
Another thing is that I use weights from official yolov5 as pretrained weight, cause I thought this might get better results, so I didn't start training from scratch.

**Comment by Laughing-q** [comment]
@AyushExel If you need, I think I can send you my training results.

**Comment by Laughing-q** [comment]
@AyushExel Please let me know if you have any progress！

**Comment by AyushExel** [comment]
@Laughing-q yes I think we can do some architectural experiments on the head. I think solov2 had some nice results so maybe we should experiment with its head. I'm working slowly to get this branch ready for experimentation..

Yes I'll keep you updated with my progress and we can even collaborate on ideas. I'll let you know.. Do you have any email where I can reach you ?

**Comment by Laughing-q** [comment]
@AyushExel here is my email. laughingq@163.com, feel free to reach me if you need any help about this instance segmentation plan.

**Comment by AyushExel** [comment]
@Laughing-q Great! I'll keep you up to speed

**Comment by Laughing-q** [comment]
@AyushExel I believe that putting pred_masks to cpu operation costs much time.[https://github.com/Laughing-q/yolov5-q/blob/39611ff6c113a23b102c00248855f7ecb17379e8/yolov5/core/evaluator.py#L222](https://github.com/Laughing-q/yolov5-q/blob/39611ff6c113a23b102c00248855f7ecb17379e8/yolov5/core/evaluator.py#L222)
Plotting needs the pred_masks in cpu instead of cuda, and the pred_masks is Nx640x640 when mask_ratio=1.

**Comment by AyushExel** [comment]
@Laughing-q here N is number of detections per image right? Maybe we can look at how some existing libraries (like detectron2 etc.) solve this problem...Maybe we limit the number N (detections per image) ... How many detections per image is the evaluator plotting? Is there an upper limit?

**Comment by AyushExel** [comment]
@Laughing-q I think detectron2 does this.. when plotting, limit the number of detection instances.. I think its set to 10 or 20..10 instances per image should be enough for plotting I think.. It can be an argument in `plot_images_and_masks` like `max_preds_per_img=10` https://github.com/Laughing-q/yolov5-q/blob/39611ff6c113a23b102c00248855f7ecb17379e8/yolov5/utils/plots.py#L695

**Comment by Laughing-q** [comment]
@AyushExel  yes I limited the number of detections to 10 in every single image. It does speed up the evaluation.

**Comment by AyushExel** [comment]
Interesting...I didn't see this much speed down on detectron2..Hmm need to think about this.. Do you have any other ideas for speeding up( both evaluation plots, and training ) ?

**Comment by AyushExel** [comment]
@glenn-jocher Yep I'm trying to see where we are with the vanilla segmentation head attached alongside detection. I've got some initial results and I'll let it train for 10epochs.. Optimisation is mostly what I'll focus on before experimenting with various heads.

**Comment by glenn-jocher** [comment]
@AyushExel also BTW the YOLOv5 dataloader always caches the **labels** into RAM (both yolo-box and yolo-segments). --cache only affects the **images**, so if the new segmentats dataloader is reading the segments every time this might be a slowdown.

**Comment by Laughing-q** [comment]
@AyushExel I think that the evaluation in detectron2 is faster in total(I don't test it yet, just a thought), cause they use coco API to eval the mask mAP, but I compute the mask iou manually like yolov5. About plotting, the format of masks in detecrtron2 is polygon points, which use `matplotlib` to plot. 
[https://github.com/facebookresearch/detectron2/blob/453d795eb152f7210c842674810f24769d4dd8cb/detectron2/utils/visualizer.py#L1136](https://github.com/facebookresearch/detectron2/blob/453d795eb152f7210c842674810f24769d4dd8cb/detectron2/utils/visualizer.py#L1136), I don't know if it will be faster.
Also I agree with @glenn-jocher , the evaluation during training will compute the loss, and the way I compute loss might slow down the speed. 
As for the dataloader, segments will be cached into RAM like official yolov5.

**Comment by AyushExel** [comment]
Okay I'll the yolov5s model train for a few epochs now.. And then start investigating the bottleneck

**Comment by glenn-jocher** [comment]
@AyushExel I forgot to mention, you should check `nvidia-smi` to get a read on the utilization during training. Low utilization rates are usually caused by a slow dataloader or lots of cpu <-> cuda transfers. Or they could indicate validation is happening. 

- Training utilization should average 90%
- Validation utilization should average 20% (a lot of time is spent computing mAP, I wonder if we could multithread this)

Something seems off with device 7 BTW. It's used up a lot of CUDA memory and sitting at 0% utilization:
<img width="948" alt="Screen Shot 2022-07-12 at 1 06 14 PM" src="https://user-images.githubusercontent.com/26833433/178476361-7251bf54-64bc-47ac-98f3-0b8085cb255a.png">

**Comment by AyushExel** [comment]
@glenn-jocher yep that's exactly the case..As @Laughing-q mentioned transferring mask from cuda to cpu, utilisation is almost none

**Comment by AyushExel** [comment]
@Laughing-q sent you a mail

**Comment by Laughing-q** [comment]
> @Laughing-q sent you a mail

I suppose I have replied to you an hour ago. Didn't you receive it？ I'll send it again, please check again.

**Comment by AyushExel** [comment]
@Laughing-q @glenn-jocher I'll move this discussion to a PR thread soon. But one of the low hanging fruits that I think might improve the performance slightly is using `torch.no_grad` when computing loss which wasn't used for computing seg loss.

**Comment by AyushExel** [comment]
We've come a long way since this ..but closing this issue :)))
